import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { coinGecko } from "@/lib/providers/coingecko";
import { getBinanceOrder } from "@/lib/providers/binance";
import { tradingAssets } from "@/lib/trading";
import { rejectCrossSiteMutation } from "@/lib/security/request";
const liveStatuses:Record<string,string>={NEW:"open",PENDING_NEW:"open",PARTIALLY_FILLED:"partially_filled",FILLED:"filled",CANCELED:"cancelled",REJECTED:"rejected",EXPIRED:"rejected",EXPIRED_IN_MATCH:"rejected"};
export async function POST(request:Request){const crossSite=rejectCrossSiteMutation(request);if(crossSite)return crossSite;const supabase=await createClient();const admin=createAdminClient();if(!supabase||!admin)return NextResponse.json({error:"Trading storage is unavailable."},{status:503});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});const mode=(new URL(request.url).searchParams.get("mode")==="live"?"live":"paper") as "live"|"paper";const {data:account}=await admin.from("trading_accounts").select("id").eq("user_id",user.id).eq("mode",mode).maybeSingle();if(!account)return NextResponse.json({checked:0,updated:0});const {data:orders,error}=await admin.from("trading_orders").select("id,pair,provider,external_order_id,status").eq("account_id",account.id).in("status",["open","partially_filled"]).limit(100);if(error)return NextResponse.json({error:error.message},{status:500});let updated=0;const failures:string[]=[];if(mode==="paper"){const symbols=[...new Set((orders??[]).map(o=>o.pair.split("/")[0]))].filter((s):s is keyof typeof tradingAssets=>s in tradingAssets);const prices=symbols.length?await coinGecko.prices(symbols.map(s=>tradingAssets[s])):{};for(const order of orders??[]){const symbol=order.pair.split("/")[0] as keyof typeof tradingAssets;const price=prices[tradingAssets[symbol]]?.price;if(!price)continue;const result=await admin.rpc("process_paper_order",{order_id:order.id,market_price:price,fee_rate:.001});if(!result.error&&result.data?.status!=="open")updated++}}else{for(const order of orders??[]){if(!order.external_order_id)continue;try{const remote=await getBinanceOrder(order.pair.replace("/",""),order.external_order_id);const status=liveStatuses[String(remote.status)]??"open";const executed=Number(remote.executedQty??0);const quote=Number(remote.cummulativeQuoteQty??0);const result=await admin.from("trading_orders").update({status,executed_quantity:executed,fill_price:executed>0?quote/executed:null,provider_updated_at:new Date().toISOString(),filled_at:status==="filled"?new Date().toISOString():null,cancelled_at:status==="cancelled"?new Date().toISOString():null}).eq("id",order.id);if(result.error)throw result.error;updated++}catch(error){failures.push(`${order.id}: ${error instanceof Error?error.message:"failed"}`)}}}return NextResponse.json({checked:orders?.length??0,updated,failures})}
