import Image from "next/image";
import Link from "next/link";
import { IconApi, IconBell, IconChartLine, IconDatabase, IconLock, IconRadar, IconShieldCheck, IconTargetArrow, IconUsers, IconWorld } from "@tabler/icons-react";

export function CompanyExperience() {
  const stats = [[IconUsers,"2.4M+","Active Users"],[IconWorld,"150+","Countries"],[IconChartLine,"50M+","Data Points / Day"],[IconLock,"99.99%","Platform Uptime"],[IconDatabase,"250+","Exchange Sources"],[IconShieldCheck,"24/7","Global Support"]];
  const features = [[IconDatabase,"Real-time Markets","Live prices, depth and global market data streaming in real time."],[IconChartLine,"Advanced Charts","Professional charting with indicators and drawing tools."],[IconRadar,"Market Insights","Expert analysis and transparent market intelligence."],[IconTargetArrow,"Portfolio Tracking","Track performance and analyse holdings in one place."],[IconBell,"Alerts & Signals","Custom alerts and smart signals so you never miss a move."],[IconApi,"API Access","Developer-friendly APIs for seamless market integration."]];
  return (
    <div className="container-shell py-10">
      <section className="surface relative min-h-[470px] overflow-hidden p-8 sm:p-12"><Image src="/images/network-globe.png" alt="A connected global market network" fill priority sizes="(max-width: 1024px) 100vw, 70vw" className="object-cover object-center opacity-85"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#0a0f12_0%,rgba(10,15,18,.91)_30%,rgba(10,15,18,.13)_72%)]"/><div className="relative z-10 max-w-lg"><span className="text-xs text-muted">Company</span><h1 className="mt-6 text-5xl font-semibold leading-[1.02] tracking-[-.05em]">Built for clarity.<br/>Driven by <span className="text-[var(--amber)]">trust.</span></h1><p className="mt-6 max-w-md leading-7 text-[#abb4ba]">Korvesta exists to make global markets transparent, accessible and intuitive for everyone.</p><div className="mt-7 flex gap-3"><a href="#mission" className="gold-button">Our Mission</a><a href="#ecosystem" className="ghost-button bg-black/25">See How We Work</a></div></div></section>
      <section className="surface relative z-10 -mt-7 mx-4 grid grid-cols-2 gap-px overflow-hidden bg-[var(--border)] lg:grid-cols-6">{stats.map(([Icon,value,label])=><div key={String(label)} className="bg-[var(--surface)] p-5 text-center"><Icon size={22} className="mx-auto text-[var(--amber)]"/><strong className="mt-2 block text-xl">{String(value)}</strong><span className="text-[10px] text-muted">{String(label)}</span></div>)}</section>
      <section id="ecosystem" className="py-12"><div className="mb-5"><h2 className="text-xl font-semibold">The Korvesta Ecosystem</h2><p className="mt-1 text-xs text-muted">Powerful tools and real-time data for confident decisions.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{features.map(([Icon,title,copy])=><article key={String(title)} className="surface p-5"><Icon size={24} className="text-[var(--amber)]"/><h3 className="mt-5 text-sm font-semibold">{String(title)}</h3><p className="mt-2 text-xs leading-5 text-muted">{String(copy)}</p></article>)}</div></section>
      <section id="mission" className="grid gap-4 lg:grid-cols-2"><article className="surface flex gap-5 p-7"><IconTargetArrow size={52} stroke={1.2} className="shrink-0 text-[var(--amber)]"/><div><h2 className="text-xl font-semibold">Our Mission</h2><p className="mt-3 leading-7 text-muted">To democratise access to global financial markets through transparent data, innovative tools and unwavering integrity.</p><Link href="#" className="mt-5 inline-block text-xs font-semibold text-[var(--amber)]">Learn more about our mission →</Link></div></article><article className="surface flex gap-5 p-7"><IconWorld size={52} stroke={1.2} className="shrink-0 text-[var(--amber)]"/><div><h2 className="text-xl font-semibold">Our Vision</h2><p className="mt-3 leading-7 text-muted">A world where every investor, everywhere, can make smarter decisions with confidence and clarity.</p><Link href="#" className="mt-5 inline-block text-xs font-semibold text-[var(--amber)]">See our vision for the future →</Link></div></article></section>
      <section className="py-12"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-semibold">Leadership Team</h2><p className="mt-1 text-xs text-muted">Experienced leaders passionate about markets and technology.</p></div><a className="text-xs text-[var(--amber)]">View all team →</a></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["AM","Arjun Mehta","CEO & Co-Founder"],["SL","Sophia Lin","CTO & Co-Founder"],["MR","Michael Reyes","Head of Product"],["EP","Elena Petrova","Head of Operations"],["DO","David Okafor","Head of Data"]].map(([initials,name,role])=><article key={name} className="surface flex items-center gap-4 p-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[var(--surface-3)] font-semibold text-[var(--amber)]">{initials}</span><div><h3 className="text-sm font-semibold">{name}</h3><p className="mt-1 text-[10px] text-muted">{role}</p></div></article>)}</div></section>
      <section className="surface p-6"><h2 className="text-sm font-semibold">Trusted by Leading Partners</h2><div className="mt-7 grid grid-cols-2 gap-7 text-center text-lg font-semibold text-muted sm:grid-cols-3 lg:grid-cols-6"><span>BINANCE</span><span>coinbase</span><span>kraken</span><span>CME Group</span><span>TRADINGVIEW</span><span>aws</span></div><p className="mt-6 text-center text-[10px] text-muted">And 100+ more global data and infrastructure partners.</p></section>
      <section className="mt-4 grid gap-4 lg:grid-cols-2"><article className="surface flex gap-6 p-7"><IconShieldCheck size={64} stroke={1.1} className="text-[var(--amber)]"/><div><h2 className="font-semibold">Security You Can Rely On</h2><ul className="mt-4 grid gap-2 text-xs text-muted"><li>● Bank-level encryption</li><li>● SOC 2 Type II certified</li><li>● Regular security audits</li><li>● 24/7 threat monitoring</li></ul></div></article><article className="surface flex gap-6 p-7"><IconLock size={64} stroke={1.1} className="text-[var(--amber)]"/><div><h2 className="font-semibold">Compliance & Transparency</h2><ul className="mt-4 grid gap-2 text-xs text-muted"><li>● KYC/AML compliant</li><li>● Global regulatory standards</li><li>● Transparent operations</li><li>● User data protection</li></ul></div></article></section>
    </div>
  );
}
