"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useState } from "react";
import { IconBuildingBank,IconChartLine,IconLock,IconMail,IconShieldCheck,IconTargetArrow,IconUsers,IconWorld,IconX } from "@tabler/icons-react";
export function CompanyExperience(){const [contact,setContact]=useState(false);useEffect(()=>{if(!contact)return;const key=(e:KeyboardEvent)=>e.key==="Escape"&&setContact(false);window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[contact]);return <div className="container-shell py-10">
 <section className="surface relative min-h-[470px] overflow-hidden p-8 sm:p-12"><Image src="/images/network-globe.png" alt="A connected global fixed-income network" fill priority sizes="(max-width:1024px) 100vw,70vw" className="object-cover opacity-80"/><div className="absolute inset-0 bg-[linear-gradient(90deg,#0a0f12_0%,rgba(10,15,18,.92)_35%,rgba(10,15,18,.15)_75%)]"/><div className="relative z-10 max-w-lg"><span className="text-xs text-muted">Company</span><h1 className="mt-6 text-5xl font-semibold leading-[1.02] tracking-[-.05em]">Built for steady progress.<br/>Driven by <span className="text-[var(--amber)]">trust.</span></h1><p className="mt-6 leading-7 text-[#abb4ba]">Korvesta helps investors understand Treasury bonds, fixed income and ETFs through clear education and thoughtful tools.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/whitepaper#mission" className="gold-button">Our Mission</Link><Link href="/whitepaper#vision" className="ghost-button bg-black/25">Our Vision</Link></div></div></section>
 <section className="py-12"><div className="mb-5"><h2 className="text-xl font-semibold">The Korvesta Fixed-Income Ecosystem</h2><p className="mt-1 text-xs text-muted">Focused tools for long-term, income-oriented decisions.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[IconBuildingBank,"Treasury Research","Understand bills, notes, bonds and the yield curve."],[IconChartLine,"Bond ETF Comparison","Compare duration, yield, expenses and portfolio exposure."],[IconShieldCheck,"Risk Education","Learn about rate, credit, liquidity and inflation risk."],[IconWorld,"Macro Insights","Connect policy, inflation and growth to fixed-income markets."]].map(([Icon,t,c])=><article key={String(t)} className="surface p-5"><Icon size={25} className="text-[var(--amber)]"/><h3 className="mt-5 font-semibold">{String(t)}</h3><p className="mt-2 text-xs leading-5 text-muted">{String(c)}</p></article>)}</div></section>
 <section className="grid gap-4 lg:grid-cols-2"><article id="mission" className="surface flex gap-5 p-7"><IconTargetArrow size={52} className="shrink-0 text-[var(--amber)]"/><div><h2 className="text-xl font-semibold">Our Mission</h2><p className="mt-3 leading-7 text-muted">To make bonds, Treasury securities and ETFs understandable and accessible through disciplined education and transparent tools.</p><Link href="/whitepaper#mission" className="mt-5 inline-block text-xs font-semibold text-[var(--amber)]">Read the detailed mission →</Link></div></article><article id="vision" className="surface flex gap-5 p-7"><IconWorld size={52} className="shrink-0 text-[var(--amber)]"/><div><h2 className="text-xl font-semibold">Our Vision</h2><p className="mt-3 leading-7 text-muted">A future where every investor can use fixed income confidently to preserve capital, earn income and pursue durable goals.</p><Link href="/whitepaper#vision" className="mt-5 inline-block text-xs font-semibold text-[var(--amber)]">Read the detailed vision →</Link></div></article></section>
 <section className="py-12"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-semibold">Management Team</h2><p className="mt-1 text-xs text-muted">A multidisciplinary team across investment research, product, risk and operations.</p></div><button type="button" onClick={()=>setContact(true)} className="text-xs text-[var(--amber)]">Message management →</button></div><button type="button" onClick={()=>setContact(true)} className="surface flex w-full items-center gap-5 p-6 text-left transition hover:border-[var(--amber)]"><span className="grid h-14 w-14 place-items-center rounded-full bg-[var(--surface-3)] text-[var(--amber)]"><IconUsers size={27}/></span><div className="flex-1"><h3 className="font-semibold">Korvesta Management</h3><p className="mt-1 text-xs text-muted">Investment research, technology, compliance and client experience</p></div><IconMail className="text-[var(--amber)]"/></button></section>
 <section className="surface grid gap-5 p-7 md:grid-cols-2"><div className="flex gap-4"><IconShieldCheck size={45} className="text-[var(--amber)]"/><div><h2 className="font-semibold">Security you can rely on</h2><p className="mt-2 text-xs leading-5 text-muted">Layered account protection, careful access controls and continuous monitoring.</p></div></div><div className="flex gap-4"><IconLock size={45} className="text-[var(--amber)]"/><div><h2 className="font-semibold">Clarity and transparency</h2><p className="mt-2 text-xs leading-5 text-muted">Plain-language product information, risk education and transparent operating principles.</p></div></div></section>
 {contact?<div role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setContact(false)} className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" aria-labelledby="management-title" className="surface w-full max-w-lg p-7"><div className="flex items-start justify-between"><div><h2 id="management-title" className="text-2xl font-semibold">Message management</h2><p className="mt-2 text-sm text-muted">Contact the Korvesta management team directly.</p></div><button type="button" onClick={()=>setContact(false)} aria-label="Close contact dialog" className="ghost-button h-10 min-h-10 w-10 p-0"><IconX size={18}/></button></div><div className="mt-6 rounded-xl border p-5" style={{borderColor:"var(--border)"}}><span className="text-xs text-muted">Management email</span><a className="mt-2 block text-lg font-semibold text-[var(--amber)]" href="mailto:management@korvesta.org">management@korvesta.org</a></div><a href="mailto:management@korvesta.org?subject=Message%20for%20Korvesta%20Management" className="gold-button mt-5 w-full"><IconMail size={17}/> Open email composer</a></div></div>:null}
 </div>}
