import Link from "next/link";
import { IconArrowRight,IconBuildingBank,IconChartDots3,IconLock,IconScale,IconWorldSearch } from "@tabler/icons-react";
import { assets } from "@/lib/data";
import { MarketStatCard } from "./MarketCards";
import { LightweightMarketChart } from "./LightweightMarketChart";
import { LiveAssetCard } from "./LiveAssetCard";
export function HomeExperience(){return <>
 <section className="container-shell grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[.82fr_1.18fr]"><div><p className="kicker">Fixed income. Clearer decisions.</p><h1 className="mt-5 max-w-[680px] text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl xl:text-[72px]">Build lasting wealth with <span className="amber-text">bonds & ETFs.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted sm:text-lg">Discover Treasury bonds, government securities and diversified bond ETFs with practical research built for long-term investors.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/markets" className="gold-button">Explore Bond Markets <IconArrowRight size={18}/></Link><Link href="/learn" className="ghost-button">Learn Fixed Income</Link></div><div className="mt-9 grid max-w-[620px] grid-cols-3 gap-4 text-xs text-muted">{[[IconBuildingBank,"Treasury focus","Bills, notes & bonds"],[IconChartDots3,"ETF research","Compare diversified funds"],[IconLock,"Investor first","Clarity and discipline"]].map(([Icon,t,s])=><div key={String(t)} className="flex gap-2"><Icon size={20} className="text-[var(--amber)]"/><div><strong className="block text-[var(--text)]">{String(t)}</strong><span>{String(s)}</span></div></div>)}</div></div>
 <div className="surface grid-bg overflow-hidden p-6 sm:p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-[var(--amber)] font-bold text-black">B</span><div><strong>Total Bond Market ETF</strong><span className="ml-3 text-xs text-muted">BND</span></div></div><div className="text-right"><strong className="metric-value block text-3xl">{assets[2].price}</strong><span className="text-xs text-[#28c76f]">Live</span></div></div><LightweightMarketChart asset="BND" days={30} height={260}/><div className="grid grid-cols-2 gap-3 border-t pt-5 text-xs sm:grid-cols-4" style={{borderColor:"var(--border)"}}>{[["Category","Broad bonds"],["Structure","ETF"],["Risk profile","Diversified"],["Coverage","US market"]].map(([l,v])=><div key={l}><span className="block text-muted">{l}</span><strong className="mt-1.5 block text-sm">{v}</strong></div>)}</div></div></section>
 <section className="container-shell py-6"><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-semibold">Fixed-Income Snapshot</h2><p className="mt-1 text-xs text-muted">Key rates and diversified funds at a glance</p></div><Link href="/markets" className="text-xs text-muted hover:text-[var(--amber)]">View all markets →</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MarketStatCard label="2-Year Treasury" value="4.71%" change={-.02} data={assets[1].data}/><MarketStatCard label="10-Year Treasury" value="4.28%" change={-.04} data={assets[0].data}/><MarketStatCard label="BND ETF" value="$72.84" change={.18} data={assets[2].data}/><MarketStatCard label="TLT ETF" value="$92.35" change={.62} data={assets[4].data}/></div></section>
 <section className="container-shell py-14"><div className="mb-5"><h2 className="text-xl font-semibold">Bond, ETF & Digital Asset Snapshot</h2><p className="mt-1 text-xs text-muted">Fixed income remains central, with a small digital-asset view</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[...assets.slice(2,6),assets[8]].map(a=><LiveAssetCard key={a.symbol} asset={a}/>)}</div></section>
 <section className="container-shell pb-14"><div className="surface grid gap-4 p-7 lg:grid-cols-3">{[[IconBuildingBank,"Treasury Centre","Compare short-, intermediate- and long-term government securities.","/markets"],[IconWorldSearch,"Fixed-Income Insights","Understand rates, inflation, credit spreads and the yield curve.","/insights"],[IconScale,"Bond ETF Education","Learn how cost, duration and holdings shape a bond ETF.","/learn"]].map(([Icon,t,d,h])=><article key={String(t)} className="surface-soft p-6"><Icon size={34} className="text-[var(--amber)]"/><h3 className="mt-5 text-lg font-semibold">{String(t)}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted">{String(d)}</p><Link href={String(h)} className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[var(--amber)]">Explore <IconArrowRight size={14}/></Link></article>)}</div></section>
 </>}
