"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { IconArrowRight, IconBookmark, IconBuildingBank, IconChartCandle, IconCoins, IconMail, IconSearch, IconStack2 } from "@tabler/icons-react";
import { assets, news } from "@/lib/data";
import { Candles, Sparkline } from "./Charts";
import { MarketStatCard } from "./MarketCards";

const artIcons = [IconStack2, IconBuildingBank, IconCoins, IconChartCandle];

export function InsightsExperience() {
  const [subscribed, setSubscribed] = useState(false);
  const subscribe = (e: FormEvent) => { e.preventDefault(); setSubscribed(true); };
  return (
    <div className="container-shell py-11">
      <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-4xl font-semibold tracking-[-.04em]">Insights</h1><p className="mt-2 text-sm text-muted">Actionable market intelligence. Curated by experts.</p></div><label className="relative"><IconSearch size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted"/><input className="field w-full min-w-[280px]" placeholder="Search insights..."/></label></div>
      <section className="surface mt-7 grid overflow-hidden lg:grid-cols-[.82fr_1.18fr_250px]"><div className="p-6 sm:p-8"><div className="flex items-center gap-3 text-[10px] text-muted"><span className="rounded bg-[#fff4c7] px-2 py-1 font-semibold text-[#a97900]">FEATURED INSIGHT</span><span>May 24, 2026</span><span>8 min read</span></div><h2 className="mt-5 text-3xl font-semibold leading-tight tracking-[-.035em]">Bitcoin breaks important range: what traders should watch next</h2><p className="mt-4 leading-7 text-muted">BTC pushes above $68K as spot demand strengthens. We analyse support levels, on-chain signals and the conditions that could drive the next move.</p><div className="mt-7 flex gap-3"><button className="gold-button">Read Full Insight</button><button className="ghost-button"><IconBookmark size={17}/> Save</button></div></div><div className="grid-bg self-stretch p-5"><Candles/></div><aside className="border-l p-5" style={{borderColor:"var(--border)"}}><h3 className="font-semibold">Economic Calendar</h3>{[["May 24 · 06:30","Core PCE Price Index"],["May 24 · 10:00","Consumer Sentiment"],["May 25 · 14:30","New Home Sales"]].map(([time,event])=><div key={event} className="border-b py-4" style={{borderColor:"var(--border-soft)"}}><span className="text-[10px] text-muted">{time}</span><strong className="mt-1 block text-xs">{event}</strong><span className="mt-2 inline-block text-[10px] text-[var(--amber)]">●●● High impact</span></div>)}</aside></section>
      <section className="mt-9"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">Analyst Commentary</h2><a className="text-xs text-muted">View all analysis →</a></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[["Maya Chen","Head of Research","BTC momentum builds as liquidity improves."],["Daniel Brooks","Macro Strategist","Rate-cut odds rise, but Q3 data still matters."],["Arjun Patel","On-chain Analyst","Exchange reserves remain structurally low."],["Sophia Lee","Market Analyst","Altcoins show relative strength rotation."]].map(([name,role,copy],i)=><article key={name} className="surface p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[var(--surface-3)] font-semibold text-[var(--amber)]">{name[0]}</span><div><strong className="block text-sm">{name}</strong><span className="text-[10px] text-muted">{role}</span></div></div><p className="mt-4 text-sm leading-6 text-muted">{copy}</p><Sparkline data={assets[i].data} positive height={45}/><span className="text-[10px] text-muted">May 24, 2026</span></article>)}</div></section>
      <section className="mt-10"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">Market News</h2><a className="text-xs text-muted">View all news →</a></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{news.map((item,i)=>{const Icon=artIcons[i];return <article key={item.title} className="surface group overflow-hidden"><div className="grid h-40 place-items-center bg-[var(--surface-2)]"><Icon size={70} stroke={1.1} className="text-[var(--amber)] transition-transform duration-500 group-hover:scale-110"/></div><div className="p-5"><div className="flex gap-3 text-[10px]"><span className="text-[var(--amber)]">{item.tag}</span><span className="text-muted">{item.time}</span></div><h3 className="mt-3 text-lg font-semibold leading-6">{item.title}</h3><p className="mt-2 text-xs leading-5 text-muted">{item.excerpt}</p><Link href="#" className="mt-4 inline-flex items-center gap-1 text-xs font-medium">Read more <IconArrowRight size={13}/></Link></div></article>})}</div></section>
      <section className="mt-10"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">Major Indexes</h2><a className="text-xs text-muted">View all indexes →</a></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MarketStatCard label="S&P 500" value="5,303.27" change={.68} data={assets[0].data}/><MarketStatCard label="NASDAQ 100" value="18,550.12" change={.85} data={assets[1].data}/><MarketStatCard label="DOW JONES" value="38,872.99" change={.8} data={assets[4].data}/><MarketStatCard label="GOLD" value="2,345.68" change={.31} data={assets[2].data}/><MarketStatCard label="OIL (WTI)" value="78.56" change={-1.67} data={assets[5].data}/></div></section>
      <form onSubmit={subscribe} className="surface mt-10 flex flex-col items-start gap-5 bg-[linear-gradient(90deg,rgba(255,196,0,.13),transparent)] p-6 lg:flex-row lg:items-center"><IconMail size={40} className="text-[var(--amber)]"/><div className="flex-1"><h2 className="font-semibold">Stay ahead with expert insights</h2><p className="mt-1 text-xs text-muted">Join traders and investors who receive our weekly market outlook.</p></div><input required type="email" className="field max-w-sm px-4" placeholder="Enter your email"/><button className="gold-button">{subscribed?"Subscribed ✓":"Subscribe"}</button></form>
    </div>
  );
}
