"use client";

import { useState } from "react";
import { IconBook2, IconBrandYoutube, IconChartCandle, IconChevronRight, IconClock, IconCoinBitcoin, IconPlayerPlay, IconSearch, IconShieldCheck } from "@tabler/icons-react";
import { lessons } from "@/lib/data";
import { Candles } from "./Charts";

export function LearnExperience() {
  const [answer, setAnswer] = useState<string | null>(null);
  return (
    <div className="container-shell py-11">
      <section className="relative overflow-hidden rounded-2xl border bg-[var(--surface)] p-8 sm:p-10" style={{borderColor:"var(--border)"}}><div className="relative z-10 max-w-2xl"><h1 className="text-5xl font-semibold tracking-[-.05em]">Learn. Trade. <span className="text-[var(--amber)]">Grow.</span></h1><p className="mt-4 max-w-xl leading-7 text-muted">Build your knowledge with actionable lessons, expert content and practical tools.</p><label className="relative mt-6 block max-w-md"><IconSearch size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted"/><input className="field" placeholder="Search lessons, guides, topics..."/></label></div><div className="absolute -right-10 -top-10 hidden h-72 w-[46%] opacity-35 lg:block"><Candles/></div></section>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[IconBook2,"Getting Started","Start your journey"],[IconCoinBitcoin,"Trading Basics","Core concepts"],[IconChartCandle,"Technical Analysis","Read charts"],[IconBrandYoutube,"On-chain & DeFi","Explore blockchain"],[IconShieldCheck,"Risk Management","Protect capital"]].map(([Icon,title,copy])=><button key={String(title)} className="surface flex items-center gap-3 p-4 text-left hover:border-[var(--amber)]"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[var(--surface-3)] text-[var(--amber)]"><Icon size={20}/></span><span><strong className="block text-xs">{String(title)}</strong><small className="text-muted">{String(copy)}</small></span></button>)}</div>
      <section className="mt-10"><div className="mb-4 flex justify-between"><h2 className="text-xl font-semibold">Beginner Guides</h2><a className="text-xs text-muted">View all guides →</a></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{lessons.map((lesson)=><article key={lesson.title} className="surface group overflow-hidden"><div className="bg-[var(--surface-2)] p-6"><Candles/></div><div className="p-5"><h3 className="font-semibold">{lesson.title}</h3><p className="mt-2 min-h-10 text-xs leading-5 text-muted">{lesson.desc}</p><div className="mt-4 flex items-center justify-between text-[10px]"><span className="text-[var(--amber)]">{lesson.level} · {lesson.time}</span><button className="grid h-8 w-8 place-items-center rounded-full border group-hover:border-[var(--amber)]" style={{borderColor:"var(--border)"}}><IconChevronRight size={15}/></button></div></div></article>)}</div></section>
      <div className="mt-5 grid gap-4 xl:grid-cols-[1.2fr_.8fr_.75fr]"><section className="surface p-5"><h2 className="font-semibold">Chart Reading Lessons</h2><div className="mt-4 grid gap-1">{[["Trend Analysis","12 min"],["Support & Resistance","10 min"],["Chart Patterns","14 min"],["Indicators 101","16 min"]].map(([title,time])=><button key={title} className="flex items-center gap-3 rounded-lg border-b px-2 py-3 text-left hover:bg-[var(--surface-2)]" style={{borderColor:"var(--border-soft)"}}><IconPlayerPlay size={16} className="text-[var(--amber)]"/><span className="flex-1 text-xs font-medium">{title}</span><span className="text-[10px] text-muted">{time}</span></button>)}</div></section><section className="surface p-5"><h2 className="font-semibold">Glossary</h2><div className="mt-4 grid gap-4">{[["Bull Market","Prices are rising or expected to rise."],["Liquidity","The ease with which an asset can be traded."],["Volatility","The degree of price variation."],["Drawdown","A decline from peak to trough."]].map(([term,def])=><div key={term}><strong className="text-xs">{term}</strong><p className="mt-1 text-[10px] leading-4 text-muted">{def}</p></div>)}</div></section><section className="surface p-5"><span className="text-[10px] text-muted">KNOWLEDGE CHECK</span><h2 className="mt-4 font-semibold leading-6">Which indicator identifies overbought conditions?</h2><div className="mt-5 grid gap-2">{["RSI","MACD","Bollinger Bands","Moving Average"].map((a,i)=><button onClick={()=>setAnswer(a)} key={a} className={`flex items-center gap-3 rounded-lg border p-3 text-left text-xs ${answer===a?(i===0?"border-[#28c76f] text-[#28c76f]":"border-[#ff4d43] text-[#ff4d43]"):"border-[var(--border)]"}`}><span className="grid h-6 w-6 place-items-center rounded-full border">{String.fromCharCode(65+i)}</span>{a}</button>)}</div>{answer&&<p className="mt-4 text-xs text-muted">{answer==="RSI"?"Correct. RSI commonly measures overbought and oversold momentum.":"Try again. Consider the momentum oscillator bounded between 0 and 100."}</p>}</section></div>
      <section className="mt-10"><div className="mb-4 flex justify-between"><h2 className="text-xl font-semibold">Webinars & Events</h2><a className="text-xs text-muted">View all sessions →</a></div><div className="grid gap-4 lg:grid-cols-3">{[["LIVE WEBINAR","Reading Charts Like a Pro","May 29 · 12:00 PM UTC"],["WEBINAR","On-chain Insights for Traders","Jun 5 · 03:00 PM UTC"],["LIVE Q&A","Ask Me Anything","Jun 12 · 01:00 PM UTC"]].map(([tag,title,date])=><article key={title} className="surface p-5"><span className="rounded bg-[#5a3027] px-2 py-1 text-[9px] font-bold text-[#ff9b84]">{tag}</span><span className="ml-3 text-[10px] text-muted">{date}</span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-xs text-muted">Learn with Korvesta&apos;s market specialists in a practical live session.</p><button className="ghost-button mt-5 min-h-9 text-xs"><IconClock size={14}/> Register Now</button></article>)}</div></section>
    </div>
  );
}
