"use client";

import { FormEvent, useState } from "react";
import { IconApi, IconBook, IconBuildingBank, IconChevronDown, IconClock, IconCreditCard, IconHeadphones, IconMail, IconMessageCircle, IconSearch, IconSend, IconShieldCheck, IconTool, IconTrendingUp } from "@tabler/icons-react";
import { faq } from "@/lib/data";

export function SupportExperience() {
  const [sent, setSent] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const submit = (e: FormEvent) => { e.preventDefault(); setSent(true); };
  const topics = [[IconBook,"Getting Started","Learn the basics and set up your account."],[IconShieldCheck,"Account & Security","Manage security settings."],[IconTrendingUp,"Markets & Data","Understand data and coverage."],[IconTool,"Trading Tools","Learn to use advanced tools."],[IconCreditCard,"Billing & Payments","Payment methods and verification."],[IconHeadphones,"Technical Support","Troubleshooting and technical issues."],[IconApi,"API & Integrations","Integrate and build with Korvesta."],[IconClock,"Platform Updates","Latest updates and releases."]];
  return (
    <div className="container-shell py-11">
      <section className="grid items-center gap-8 lg:grid-cols-[1fr_.8fr]"><div><span className="text-xs text-muted">Support</span><h1 className="mt-6 text-5xl font-semibold tracking-[-.05em]">We&apos;re here to help</h1><p className="mt-4 max-w-lg leading-7 text-muted">Fast answers, real people and resources to support you at every step of your trading journey.</p></div><div className="surface relative grid h-56 place-items-center overflow-hidden"><div className="absolute h-40 w-64 rounded-3xl border bg-[var(--surface-2)] shadow-2xl" style={{borderColor:"var(--border)"}}/><IconHeadphones size={120} stroke={1.3} className="relative z-10 text-[var(--amber)]"/><IconMessageCircle size={64} className="absolute left-[25%] top-8 text-muted"/></div></section>
      <div className="mt-8 grid gap-4 xl:grid-cols-[1.5fr_.55fr]"><section className="surface p-6"><h2 className="font-semibold">Search the Help Centre</h2><label className="relative mt-4 block"><input className="field px-4 pr-14" placeholder="Search for articles, tools and guides..."/><IconSearch size={20} className="absolute right-4 top-1/2 -translate-y-1/2 text-muted"/></label></section><aside className="surface p-6"><h2 className="font-semibold">Still need help?</h2><p className="mt-2 text-xs text-muted">Our support team is available 24/7.</p><button className="gold-button mt-4 min-h-9 text-xs">Contact Support</button></aside></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_.55fr]"><div className="grid gap-4"><section className="surface p-6"><h2 className="font-semibold">Browse Help Topics</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{topics.map(([Icon,title,copy])=><button key={String(title)} className="rounded-xl border p-4 text-left transition-colors hover:border-[var(--amber)]" style={{borderColor:"var(--border)"}}><Icon size={22} className="text-[var(--amber)]"/><strong className="mt-4 block text-xs">{String(title)}</strong><p className="mt-2 text-[10px] leading-4 text-muted">{String(copy)}</p></button>)}</div><a className="mt-5 inline-block text-xs text-[var(--amber)]">View all help articles →</a></section><section className="surface p-6"><h2 className="font-semibold">Popular Questions</h2><div className="mt-4 grid">{faq.map(([q,a],i)=>{const expanded=openFaq===i;return <div key={q} className="border-b" style={{borderColor:"var(--border-soft)"}}><button type="button" onClick={()=>setOpenFaq(expanded?null:i)} aria-controls={`faq-panel-${i}`} aria-expanded={expanded} className="flex w-full items-center justify-between py-4 text-left text-sm"><span>{q}</span><IconChevronDown size={17} className={`transition-transform ${expanded?"rotate-180":""}`}/></button><p id={`faq-panel-${i}`} className={`pb-4 pr-10 text-xs leading-6 text-muted ${expanded?"":"hidden"}`}>{a}</p></div>})}</div></section></div><form action="/support" method="get" onSubmit={submit} className="surface h-fit p-6"><h2 className="font-semibold">Contact Us</h2><div className="mt-5 grid gap-4">{[["Full name","Your full name","text"],["Email address","you@example.com","email"]].map(([label,placeholder,type])=><label key={label} className="text-xs font-semibold">{label}<input required className="field mt-2 px-4" placeholder={placeholder} type={type}/></label>)}<label className="text-xs font-semibold">Subject<select className="field mt-2 px-4"><option>Select a topic</option><option>Account support</option><option>Technical issue</option><option>Billing</option></select></label><label className="text-xs font-semibold">Message<textarea required className="field mt-2 min-h-32 px-4 py-3" placeholder="How can we help you?"/></label><button className="gold-button"><IconSend size={16}/>{sent?"Message Sent":"Send Message"}</button></div></form></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_.55fr]"><section className="surface p-6"><h2 className="font-semibold">Join the Korvesta Community</h2><p className="mt-2 text-xs text-muted">Connect with traders, share ideas and stay up to date with market discussions.</p><div className="mt-5 flex flex-wrap gap-3">{["X / Twitter","Telegram","Discord","YouTube","LinkedIn"].map(s=><button key={s} className="ghost-button min-h-9 text-xs">{s}</button>)}</div></section><aside className="surface flex items-center gap-4 p-6"><IconShieldCheck size={44} className="text-[#28c76f]"/><div><h2 className="font-semibold">System Status</h2><p className="mt-2 text-xs text-[#28c76f]">All Systems Operational</p><span className="text-[10px] text-muted">Updated just now</span></div></aside></div>
      <section className="surface mt-4 grid gap-6 p-6 sm:grid-cols-2 lg:grid-cols-4">{[[IconMail,"Email Support","support@korvesta.org"],[IconMessageCircle,"Live Chat","Available 24/7 in-app"],[IconBuildingBank,"Phone Support","+1 (800) 567-6990"],[IconClock,"Response Time","< 2 minutes average"]].map(([Icon,title,copy])=><div key={String(title)} className="flex gap-3"><Icon size={22} className="text-[var(--amber)]"/><div><strong className="block text-xs">{String(title)}</strong><span className="mt-1 block text-[10px] text-muted">{String(copy)}</span></div></div>)}</section>
    </div>
  );
}
