create extension if not exists pgcrypto;

create type public.app_role as enum ('customer','support','compliance','finance','admin');
create type public.payment_status as enum ('pending','approved','rejected','cancelled');
create type public.order_status as enum ('open','filled','partially_filled','cancelled','rejected');
create type public.order_side as enum ('buy','sell');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null default '', country text, role public.app_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name,country) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.raw_user_meta_data->>'country'); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create table public.assets (id uuid primary key default gen_random_uuid(), symbol text unique not null, name text not null, coingecko_id text unique, decimals smallint not null check(decimals between 0 and 30), enabled boolean not null default true, created_at timestamptz not null default now());
create table public.networks (id uuid primary key default gen_random_uuid(), asset_id uuid not null references public.assets, name text not null, chain_id text, confirmation_target integer not null default 1 check(confirmation_target > 0), deposit_address text, enabled boolean not null default true, unique(asset_id,name));
create table public.ledger_accounts (id uuid primary key default gen_random_uuid(), owner_id uuid references public.profiles, asset_id uuid not null references public.assets, purpose text not null check(purpose in ('customer_available','customer_hold','platform_clearing','platform_fees','demo')), created_at timestamptz not null default now(), unique nulls not distinct(owner_id,asset_id,purpose));
create table public.ledger_transactions (id uuid primary key default gen_random_uuid(), reference text unique not null, kind text not null, status text not null default 'posted' check(status in ('pending','posted','reversed')), idempotency_key text unique not null, metadata jsonb not null default '{}', created_by uuid references public.profiles, created_at timestamptz not null default now());
create table public.ledger_entries (id uuid primary key default gen_random_uuid(), transaction_id uuid not null references public.ledger_transactions, account_id uuid not null references public.ledger_accounts, amount numeric(38,18) not null check(amount <> 0), created_at timestamptz not null default now());
create table public.price_snapshots (asset_id uuid not null references public.assets, currency text not null default 'usd', price numeric(38,18) not null check(price >= 0), change_24h numeric, market_cap numeric, volume_24h numeric, provider text not null, observed_at timestamptz not null, primary key(asset_id,currency,observed_at));
create table public.deposit_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles, asset_id uuid not null references public.assets, network_id uuid not null references public.networks, amount numeric(38,18) not null check(amount > 0), transaction_hash text, proof_path text, confirmations integer not null default 0, status public.payment_status not null default 'pending', review_note text, reviewed_by uuid references public.profiles, reviewed_at timestamptz, created_at timestamptz not null default now());
create unique index unique_deposit_hash on public.deposit_requests(network_id, transaction_hash) where transaction_hash is not null;
create table public.withdrawal_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles, asset_id uuid not null references public.assets, network_id uuid not null references public.networks, amount numeric(38,18) not null check(amount > 0), fee numeric(38,18) not null default 0 check(fee >= 0), destination text not null, status public.payment_status not null default 'pending', review_note text, first_approved_by uuid references public.profiles, second_approved_by uuid references public.profiles, reviewed_at timestamptz, created_at timestamptz not null default now(), check(first_approved_by is null or second_approved_by is null or first_approved_by <> second_approved_by));
create table public.demo_accounts (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references public.profiles, quote_asset_id uuid not null references public.assets, starting_balance numeric(38,18) not null default 100000, created_at timestamptz not null default now(), reset_at timestamptz not null default now());
create table public.demo_orders (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.demo_accounts, base_asset_id uuid not null references public.assets, side public.order_side not null, order_type text not null check(order_type in ('market','limit')), quantity numeric(38,18) not null check(quantity > 0), limit_price numeric(38,18), fill_price numeric(38,18), fee numeric(38,18) not null default 0, status public.order_status not null default 'open', idempotency_key text unique not null, created_at timestamptz not null default now(), filled_at timestamptz);
create table public.audit_events (id bigint generated always as identity primary key, actor_id uuid references public.profiles, action text not null, entity_type text not null, entity_id text not null, before_state jsonb, after_state jsonb, created_at timestamptz not null default now());

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('support','compliance','finance','admin')) $$;
create or replace function public.prevent_financial_mutation() returns trigger language plpgsql as $$ begin raise exception 'financial records are append-only'; end $$;
create trigger ledger_entries_immutable before update or delete on public.ledger_entries for each row execute function public.prevent_financial_mutation();
create trigger ledger_transactions_immutable before update or delete on public.ledger_transactions for each row execute function public.prevent_financial_mutation();

alter table public.profiles enable row level security; alter table public.assets enable row level security; alter table public.networks enable row level security; alter table public.ledger_accounts enable row level security; alter table public.ledger_transactions enable row level security; alter table public.ledger_entries enable row level security; alter table public.price_snapshots enable row level security; alter table public.deposit_requests enable row level security; alter table public.withdrawal_requests enable row level security; alter table public.demo_accounts enable row level security; alter table public.demo_orders enable row level security; alter table public.audit_events enable row level security;
create policy profiles_self_read on public.profiles for select using(id=auth.uid() or public.is_staff());
create policy public_assets_read on public.assets for select using(enabled);
create policy public_networks_read on public.networks for select using(enabled);
create policy own_accounts_read on public.ledger_accounts for select using(owner_id=auth.uid() or public.is_staff());
create policy own_entries_read on public.ledger_entries for select using(exists(select 1 from public.ledger_accounts a where a.id=account_id and (a.owner_id=auth.uid() or public.is_staff())));
create policy own_deposits on public.deposit_requests for select using(user_id=auth.uid() or public.is_staff());
create policy create_own_deposits on public.deposit_requests for insert with check(user_id=auth.uid() and status='pending');
create policy own_withdrawals on public.withdrawal_requests for select using(user_id=auth.uid() or public.is_staff());
create policy create_own_withdrawals on public.withdrawal_requests for insert with check(user_id=auth.uid() and status='pending');
create policy own_demo_accounts on public.demo_accounts for select using(user_id=auth.uid() or public.is_staff());
create policy own_demo_orders on public.demo_orders for select using(exists(select 1 from public.demo_accounts a where a.id=account_id and (a.user_id=auth.uid() or public.is_staff())));
create policy staff_audit_read on public.audit_events for select using(public.is_staff());
create policy price_read on public.price_snapshots for select using(true);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('payment-proofs','payment-proofs',false,10485760,array['image/png','image/jpeg','application/pdf']) on conflict(id) do nothing;
create policy proof_insert on storage.objects for insert to authenticated with check(bucket_id='payment-proofs' and (storage.foldername(name))[1]=auth.uid()::text);
create policy proof_read on storage.objects for select to authenticated using(bucket_id='payment-proofs' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_staff()));

insert into public.assets(symbol,name,coingecko_id,decimals) values ('BTC','Bitcoin','bitcoin',8),('ETH','Ethereum','ethereum',18),('USDT','Tether','tether',6),('SOL','Solana','solana',9),('BNB','BNB','binancecoin',18),('XRP','XRP','ripple',6) on conflict(symbol) do nothing;

create view public.account_balances with (security_invoker=true) as select account_id,coalesce(sum(amount),0)::numeric(38,18) balance from public.ledger_entries group by account_id;
grant select on public.account_balances to authenticated;
create or replace function public.get_portfolio_holdings() returns table(asset_id uuid,symbol text,coingecko_id text,quantity numeric) language sql stable security invoker set search_path='' as $$ select a.id,a.symbol,a.coingecko_id,coalesce(sum(e.amount),0) from public.ledger_accounts la join public.assets a on a.id=la.asset_id left join public.ledger_entries e on e.account_id=la.id where la.owner_id=auth.uid() and la.purpose='customer_available' group by a.id,a.symbol,a.coingecko_id having coalesce(sum(e.amount),0)<>0 $$;
grant execute on function public.get_portfolio_holdings() to authenticated;

create or replace function public.approve_deposit(request_id uuid, note text default null) returns void language plpgsql security definer set search_path='' as $$ declare r public.deposit_requests; customer_account uuid; clearing_account uuid; tx uuid; begin if not public.is_staff() then raise exception 'not authorised'; end if; select * into r from public.deposit_requests where id=request_id for update; if r.status <> 'pending' then raise exception 'request is not pending'; end if; if r.transaction_hash is null then raise exception 'transaction hash is required'; end if; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(r.user_id,r.asset_id,'customer_available') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into customer_account; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(null,r.asset_id,'platform_clearing') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into clearing_account; insert into public.ledger_transactions(reference,kind,idempotency_key,created_by,metadata) values('DEP-'||r.id,'deposit','deposit:'||r.id,auth.uid(),jsonb_build_object('request_id',r.id)) returning id into tx; insert into public.ledger_entries(transaction_id,account_id,amount) values(tx,customer_account,r.amount),(tx,clearing_account,-r.amount); update public.deposit_requests set status='approved',review_note=note,reviewed_by=auth.uid(),reviewed_at=now() where id=r.id; insert into public.audit_events(actor_id,action,entity_type,entity_id,after_state) values(auth.uid(),'approve','deposit',r.id::text,jsonb_build_object('amount',r.amount)); end $$;

create or replace function public.create_withdrawal(asset uuid, network uuid, amount numeric, fee numeric, destination text, request_key text) returns uuid language plpgsql security definer set search_path='' as $$ declare available uuid; hold uuid; clearing uuid; balance numeric; tx uuid; request_id uuid; begin if amount <= 0 or fee < 0 then raise exception 'invalid amount'; end if; select id into available from public.ledger_accounts where owner_id=auth.uid() and asset_id=asset and purpose='customer_available'; select coalesce(sum(e.amount),0) into balance from public.ledger_entries e where e.account_id=available; if balance < amount+fee then raise exception 'insufficient available balance'; end if; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(auth.uid(),asset,'customer_hold') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into hold; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(null,asset,'platform_clearing') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into clearing; insert into public.withdrawal_requests(user_id,asset_id,network_id,amount,fee,destination) values(auth.uid(),asset,network,amount,fee,destination) returning id into request_id; insert into public.ledger_transactions(reference,kind,idempotency_key,created_by,metadata) values('HOLD-'||request_id,'withdrawal_hold',request_key,auth.uid(),jsonb_build_object('request_id',request_id)) returning id into tx; insert into public.ledger_entries(transaction_id,account_id,amount) values(tx,available,-(amount+fee)),(tx,hold,amount+fee); return request_id; end $$;

create or replace function public.approve_withdrawal(request_id uuid, note text default null) returns text language plpgsql security definer set search_path='' as $$ declare r public.withdrawal_requests; hold uuid; clearing uuid; fee_account uuid; tx uuid; begin if not public.is_staff() then raise exception 'not authorised'; end if; select * into r from public.withdrawal_requests where id=request_id for update; if r.status <> 'pending' then raise exception 'request is not pending'; end if; if r.first_approved_by is null then update public.withdrawal_requests set first_approved_by=auth.uid(),review_note=note where id=r.id; insert into public.audit_events(actor_id,action,entity_type,entity_id) values(auth.uid(),'first_approve','withdrawal',r.id::text); return 'awaiting_second_approval'; end if; if r.first_approved_by=auth.uid() then raise exception 'second approver must be different'; end if; select id into hold from public.ledger_accounts where owner_id=r.user_id and asset_id=r.asset_id and purpose='customer_hold'; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(null,r.asset_id,'platform_clearing') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into clearing; insert into public.ledger_accounts(owner_id,asset_id,purpose) values(null,r.asset_id,'platform_fees') on conflict(owner_id,asset_id,purpose) do update set purpose=excluded.purpose returning id into fee_account; insert into public.ledger_transactions(reference,kind,idempotency_key,created_by,metadata) values('WDR-'||r.id,'withdrawal','withdrawal:'||r.id,auth.uid(),jsonb_build_object('request_id',r.id)) returning id into tx; insert into public.ledger_entries(transaction_id,account_id,amount) values(tx,hold,-(r.amount+r.fee)),(tx,clearing,r.amount),(tx,fee_account,r.fee); update public.withdrawal_requests set status='approved',second_approved_by=auth.uid(),reviewed_at=now() where id=r.id; insert into public.audit_events(actor_id,action,entity_type,entity_id) values(auth.uid(),'second_approve','withdrawal',r.id::text); return 'approved'; end $$;

revoke all on function public.approve_deposit(uuid,text) from public; revoke all on function public.approve_withdrawal(uuid,text) from public; grant execute on function public.approve_deposit(uuid,text) to authenticated; grant execute on function public.approve_withdrawal(uuid,text) to authenticated; grant execute on function public.create_withdrawal(uuid,uuid,numeric,numeric,text,text) to authenticated;
